# Generated by Django 5.1.3 on 2024-11-25 18:11

from django.db import migrations
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Gallery = apps.get_model('portfolio', 'Gallery')
    for gallery in Gallery.objects.all():
        if not gallery.slug:
            gallery.slug = slugify(gallery.name)
            gallery.save()

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_slugs),
    ]
